name: Update Packagist

on:
  push:
    tags:
      - '*'
  release:
    types: [published]

jobs:
  packagist:
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify Packagist
        run: |
          curl -XPOST -H'content-type:application/json' \
            'https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}' \
            -d'{"repository":{"url":"https://packagist.org/packages/qbejs/laravel-dto-mapper"}}'
